### PR TITLE
Build with Bazel

### PR DESCRIPTION
**Pull request by sr**
This is a work in progress/experiment for building Operator with [Bazel](https://bazel.build). Most of the `WORKSPACE` and all the `BUILDS` files were generated using codegen tools:

```
$ go get github.com/bazelbuild/rules_go/go/tools/wtool
$ go list -f '{{join .Deps "\n"}}' ./... |  xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' | xargs wtool -asis
$ go get github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle
$ gazelle -go_prefix github.com/sr/operator -mode fix "$(pwd)"
```

Running the tests:

```
sr@frida.local ~/src/github.com/sr/operator $ bazel test --test_output errors //:go_default_test
INFO: Found 1 test target...
Target //:go_default_xtest up-to-date:
  bazel-bin/go_default_xtest.a
  bazel-bin/go_default_xtest_main_test.go
  bazel-bin/go_default_xtest_main_test.a
  bazel-bin/go_default_xtest
INFO: Elapsed time: 6.931s, Critical Path: 4.06s
//:go_default_xtest                                                      PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
```

Building the whole workspace:

```
sr@frida.local ~/src/github.com/sr/operator $ bazel build --verbose_failures //...
INFO: Found 17 targets...
INFO: Elapsed time: 2.539s, Critical Path: 2.28s
```

Unfortunately it looks like the proto support isn't quite there yet, which was one of the major impetus for doing this. However, it looks like this is actively being worked so just going to play the waiting game for now.

/cc @lstoll

### CODE REVIEW

**Comment by lstoll** [comment]
Niice. Any use of gazelle here?

**Comment by sr** [comment]
@lstoll Yeah. Read the description again, first code block:

```
$ go get github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle
$ gazelle -go_prefix github.com/sr/operator -mode fix "$(pwd)"
```

**Comment by lstoll** [comment]
@sr that's what I get for looking at the code and not reading what you wrote

**Comment by sr** [comment]
This was an interesting and helpful experiment but Bazel isn't quite there yet. I'll revisit once the protobuf and go rules have matured a bit.

**Pull request closed without merging**
